name: test_api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2'
    - name: installation
      run: apt-get install make
    - name: run project
      run: make start
    - name: start test
      run: pytest
      run: echo "ğŸ This job's status is ${{ job.status }}."
   